# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf9f49b8740e3c9c9f20b3d72723cbf633dff838a6b06aaf416770d87ccd3101be50033b3b52ee24eda57caf759fbfc155389d88650d1a58c909228c4a95aa8a

test:
  secret_key_base: f056818bf9f7f78268130c4c395774f0e6d667c491f4bd52be0351385b5f87d1a71bda66094e1f943ceaf16fdb63f0a6f57ced3877b680e390075059d7df7941

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
